version: '3'

volumes:
  m2:
  node_modules:
  build:
  deps:
  cache:

services:
  postgres:
    image: postgres:14-alpine
    container_name: asciinema_dev_postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGPORT=5433

  # nginx disabled - not needed for testing, causes Pasta networking issues on Silverblue
  # nginx:
  #   image: nginx:alpine
  #   container_name: asciinema_dev_nginx
  #   network_mode: host
  #   volumes:
  #     - ../docker/nginx/asciinema.conf:/etc/nginx/conf.d/default.conf:ro
  #     - cache:/cache

  phoenix:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    image: asciinema/asciinema-server:local
    container_name: asciinema_dev_phoenix
    network_mode: host
    entrypoint: env -u MIX_ENV -u PORT
    command: mix phx.server
    depends_on:
      - postgres
    env_file: .env.development
    volumes:
      - ../uploads:/app/uploads:cached
      - node_modules:/app/assets/node_modules:cached
      - build:/app/_build:cached
      - deps:/app/deps:cached
      - m2:/root/.m2:cached
      - ../:/app:cached
      - /tmp/asciinema-web:/tmp:cached
